/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import dao.UserDao;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class UserAccount extends javax.swing.JFrame {

    /**
     * Creates new form UserAccount
     */
    UserDao user=new UserDao();
    Color tpc=new Color(153,204,255);
    Color pc=new Color(0,51,51);
    int xx,xy;
    private int uId;
    String[] value = new String[9];
    public UserAccount() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void init(){
        uId=user.getUserId(UserDashboard.jLabel3.getText());
        value=user.getUserValue(uId);
        setValue();
    }
    private void setValue(){
        jTextField15.setText(value[0]);
        jTextField16.setText(value[1]);
        jTextField17.setText(value[2]);
        jTextField18.setText(value[4]);
        jTextField22.setText(value[5]);
        jTextField19.setText(value[6]);
        jTextField20.setText(value[7]);
        jTextField21.setText(value[8]);
        jPasswordField3.setText(value[3]);
    }
      public boolean isEmpty(){
        if(jTextField16.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Username is required", "Warning",2);
            return false;
        }
        if(jTextField17.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Email address is required", "Warning",2);
            return false;
        }
        if(!jTextField17.getText().matches("^.+@.+\\..+$"))
        {
            JOptionPane.showMessageDialog(this,"Invalid email address", "Warning",2);
            return false;
        }
        if(String.valueOf(jPasswordField3.getPassword()).isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Password is required", "Warning",2);
            return false;
        }
        if(jTextField18.getText().length()>15)
        {
            JOptionPane.showMessageDialog(this,"Phone number is to long", "Warning",2);
            return false;
        }
        if(jTextField18.getText().length()<10)
        {
            JOptionPane.showMessageDialog(this,"Phone number is to short", "Warning",2);
            return false;
        }
        if(jTextField19.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Sequrity answer is required", "Warning",2);
            return false;
        }
        if(jTextField20.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Address Line 1 is required", "Warning",2);
            return false;
        }
        if(jTextField21.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Address Line 2 is required", "Warning",2);
            return false;
        }
        return true;
    }     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        btnsave2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        btnback2 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(204, 204, 204));
        jTextField15.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 103, 400, 30));

        jTextField16.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 189, 400, 30));

        jTextField17.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 269, 400, 30));

        jPasswordField3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 343, 400, 30));

        jTextField18.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 441, 400, 30));

        jTextField19.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 189, 400, 30));

        jTextField20.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 269, 400, 30));

        jTextField21.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 343, 400, 30));

        btnsave2.setBackground(new java.awt.Color(153, 204, 255));
        btnsave2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsave2.setForeground(new java.awt.Color(255, 255, 255));
        btnsave2.setText("Update");
        btnsave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsave2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 442, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("User Id");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 71, 300, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Username");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 151, 300, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Email");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 237, 300, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Password");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 311, 300, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Phone");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 403, 400, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Sequrity Qouestion");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 71, 300, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Answer");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 151, 300, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Address Line 1(State & Area)");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 237, 300, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Address Line 2(Country)");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 311, 300, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("X");
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 6, -1, 30));

        btnback2.setBackground(new java.awt.Color(153, 204, 255));
        btnback2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnback2.setForeground(new java.awt.Color(255, 255, 255));
        btnback2.setText("Delete");
        jPanel3.add(btnback2, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 442, -1, -1));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/visible.png"))); // NOI18N
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 40, 20));

        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hide.png"))); // NOI18N
        jLabel65.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel65MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 40, 20));

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(204, 204, 204));
        jTextField22.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel3.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 103, 398, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
         setVisible(false);
       UserDashboard.jPanel9.setBackground(pc);
        UserDashboard.jPanel10.setBackground(pc);
        UserDashboard.jLabel11.setForeground(tpc);
        UserDashboard.jLabel46.setVisible(true);
        UserDashboard.jLabel30.setVisible(false);
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void btnsave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsave2ActionPerformed
        // TODO add your handling code here:
        if(isEmpty()){
            if(!check()){
            int id=Integer.parseInt(jTextField15.getText());
            String username=jTextField16.getText();
            String email=jTextField17.getText();
            String password=String.valueOf(jPasswordField3.getPassword());
            String phone=jTextField18.getText();
            String seq=jTextField22.getText();
            String ans=jTextField19.getText();
            String address1=jTextField20.getText();
            String address2=jTextField21.getText(); 
            }
        }
        
    }//GEN-LAST:event_btnsave2ActionPerformed
    private boolean check(){
       String newEmail=jTextField17.getText();
       String newPhone=jTextField18.getText();
       if(newEmail.equals(value[2])&&newPhone.equals(value[4])){
           return false;
       }else{
           if(!newEmail.equals(value[2])){
               boolean x=user.isEmailExist(newEmail);
               if(x){
                  JOptionPane.showMessageDialog(this,"This email already exists", "Warning",2); 
               }
               return true;
           }
           if(!newPhone.equals(value[4])){
               boolean x=user.isPhoneExist(newPhone);
               if(x){
                  JOptionPane.showMessageDialog(this,"This phone number already exists", "Warning",2); 
               }
               return true;
           }
       }
       return false;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         for(double i=0.1;i<=1;i+=0.1)
        {
         String s=""+i;
         float f=Float.parseFloat(s);
         this.setOpacity(f);
            try {
                Thread.sleep(400);
            } catch (InterruptedException ex) {
                Logger.getLogger(UserAccount.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jLabel65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseClicked
        // TODO add your handling code here:
        jPasswordField3.setEchoChar((char)0);
        jLabel65.setVisible(false);
        jLabel40.setVisible(true);
    }//GEN-LAST:event_jLabel65MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
         jPasswordField3.setEchoChar('*');
        jLabel65.setVisible(true);
        jLabel40.setVisible(false);
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback2;
    private javax.swing.JButton btnsave2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    // End of variables declaration//GEN-END:variables
}
